# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dataverse_pb2 as dataverse__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/Greeter/Upload',
                request_serializer=dataverse__pb2.ImageUploadRequest.SerializeToString,
                response_deserializer=dataverse__pb2.ImageUploadResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/Greeter/Search',
                request_serializer=dataverse__pb2.SearchRequest.SerializeToString,
                response_deserializer=dataverse__pb2.SearchResponse.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=dataverse__pb2.ImageUploadRequest.FromString,
                    response_serializer=dataverse__pb2.ImageUploadResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=dataverse__pb2.SearchRequest.FromString,
                    response_serializer=dataverse__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Greeter/Upload',
            dataverse__pb2.ImageUploadRequest.SerializeToString,
            dataverse__pb2.ImageUploadResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Greeter/Search',
            dataverse__pb2.SearchRequest.SerializeToString,
            dataverse__pb2.SearchResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
